[package]
name = "rust_parser"
version = "0.1.0"
authors = ["Miroslav CÌŒech <miroslav.cech@gooddata.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
